nelmio_api_doc:
    documentation:
        info:
            title: "%env(APP_NAME)%"
            description: "%env(APP_DESCRIPTION)%"
            version: "%env(APP_VERSION)%"
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc|_error) # Accepts routes under /api except /api/doc
            # - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
